services:
  - type: web
    name: signlanguage-backend
    env: python
    runtime: python-3.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon  # bạn có thể đổi thành singapore nếu gần Việt Nam hơn

